/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supershop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Shawon
 */
public class CartPanel extends javax.swing.JFrame {

    /**
     * Creates new form CartPanel
     */
    
    int[] selectedRows;
    public CartPanel() {
        initComponents();
        
        try {  
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
             Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=customer;integratedSecurity=true");  
   
               Statement statement = connection.createStatement();  
               
             ResultSet rs = statement.executeQuery("SELECT C_id, C_name, Buying_item, Payment_type FROM cus_order ");  
             ResultSetMetaData  rsmetadata = rs.getMetaData(); 
              int  columns = rsmetadata.getColumnCount();   
              DefaultTableModel dtm = new DefaultTableModel(); 
              Vector columns_name=new Vector();
              Vector data_rows=new Vector();
              for(int  i= 1; i < columns+1; i++)  
                {             
                        columns_name.addElement (rsmetadata.getColumnLabel(i));  
                }                 
              
              dtm.setColumnIdentifiers(columns_name);
                   while (rs.next())  
              {  
               data_rows = new Vector(); 
               for (int j = 1; j <columns+1; j++)  
               {  
                   data_rows.addElement(rs.getString(j)) ;
               }  
               dtm.addRow(data_rows);  
               
       }   
          cart_tbl.setModel(dtm); 
          //carttable.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
             
         } catch (Exception e) {  
             e.printStackTrace();  
         }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        cart_tbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        dlt_cart = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/product_logo_icon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 20)); // NOI18N
        jLabel2.setText("  Welcome  to  Collective Mart  Shopping");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 19, 511, 39));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1013, 71);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane9.setPreferredSize(new java.awt.Dimension(1000, 340));

        cart_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "P_id", "P_name", "Stock"
            }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

            public Class getColumnClass(int columnIndex){
                return types [columnIndex];
            }

        });
        cart_tbl.setPreferredSize(new java.awt.Dimension(1000, 340));
        cart_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart_tblMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(cart_tbl);

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 1000, 420);

        jPanel3.setBackground(new java.awt.Color(0, 150, 120));

        dlt_cart.setBackground(new java.awt.Color(0, 150, 120));
        dlt_cart.setFont(new java.awt.Font("Century", 1, 15)); // NOI18N
        dlt_cart.setText("Delete");
        dlt_cart.setBorder(null);
        dlt_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlt_cartActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 150, 120));
        jButton3.setFont(new java.awt.Font("Century", 1, 15)); // NOI18N
        jButton3.setText("Buy");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(719, Short.MAX_VALUE)
                .addComponent(dlt_cart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(885, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dlt_cart, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 490, 1000, 70);

        setSize(new java.awt.Dimension(1016, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dlt_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlt_cartActionPerformed
        
        
       TableModel ct = cart_tbl.getModel();
      // cart_tbl.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
       int[] selectedRows = cart_tbl.getSelectedRows();
       
        try {  
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
             Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=supershop;integratedSecurity=true");  
   
               //Statement ps = con.createStatement(); 
            //   Statement ps = (Statement) con.createStatement();
            //   System.out.println("Database connected");
               
            // ResultSet rs = statement.executeQuery("SELECT C_id, C_name, Buying_item, Payment_type FROM cus_order ");  
             //ResultSetMetaData  rsmetadata = rs.getMetaData(); 
             // int  columns = rsmetadata.getColumnCount();   
             for (int i = 0; i < selectedRows.length; i++) {
              int row = selectedRows[i]; 
              String id = ct.getValueAt(row, 0).toString();
             // System.out.println(id);
           /*   int r = ps.executeUpdate(sql);
            if (r != 0) {
                JOptionPane.showMessageDialog(null, "Successfully deleted!", "Delete", JOptionPane.OK_OPTION);
            }else {
                JOptionPane.showMessageDialog(null, "Wait! something's wrong, please try again later.", "Ooopppss!", JOptionPane.OK_OPTION);
            }*/
           String query = "DELETE from product where p_id= ?";
           PreparedStatement preparedStmt = con.prepareStatement(query);
           preparedStmt.setString(1,id);
           preparedStmt.executeUpdate();
           }
                 try {  
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
             Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=supershop;integratedSecurity=true");  
   
               Statement statement = connection.createStatement();  
               
             ResultSet rs = statement.executeQuery("SELECT C_id, C_name, Buying_item, Payment_type FROM customer_details ");  
             ResultSetMetaData  rsmetadata = rs.getMetaData(); 
              int  columns = rsmetadata.getColumnCount();   
              DefaultTableModel dtm = new DefaultTableModel(); 
              Vector columns_name=new Vector();
              Vector data_rows=new Vector();
              for(int  i= 1; i < columns+1; i++)  
                {             
                        columns_name.addElement (rsmetadata.getColumnLabel(i));  
                }                 
              
              dtm.setColumnIdentifiers(columns_name);
                   while (rs.next())  
              {  
               data_rows = new Vector(); 
               for (int j = 1; j <columns+1; j++)  
               {  
                   data_rows.addElement(rs.getString(j)) ;
               }  
               dtm.addRow(data_rows);  
               
       }   
          cart_tbl.setModel(dtm); 
          //carttable.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
             
         } catch (Exception e) {  
             e.printStackTrace();  
         }
             
         } catch (Exception e) {  
             e.printStackTrace();  
         }
        
        
      /*        
     DefaultTableModel dtm = new DefaultTableModel(); 
      TableModel ct = cart_tbl.getModel();
      //int selectedRow = carttable.getSelectedRow();
      carttable.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
      int[] selectedRows = carttable.getSelectedRows();
      
      // StringBuilder b = new StringBuilder();
      // b.append("Delete from tbl_temp where ");
       for (int i = 0; i < selectedRows.length; i++) {
              int row = selectedRows[i]; 
              String name = model.getValueAt(row, 0).toString();
              String date = model.getValueAt(row, 1).toString();
             // b.append("(holderName = '" +name+"' AND IODate='"+date+"')");
             // if (i < selectedRows.length - 1) {
                //b.append(" OR ");  //omit the last OR 
              } 
             }
          //  st.executeUpdate(b.toString());
      
      
      
       while (selectedRow != -1)
                {
                    model.removeElementAt( row );
                    row = list.getSelectedIndex();
                }
        
        
        
        */
    }//GEN-LAST:event_dlt_cartActionPerformed

    private void cart_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_tblMouseClicked
       
      // cart_tbl.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
       //int[] selectedRows = cart_tbl.getSelectedRows();
        
    }//GEN-LAST:event_cart_tblMouseClicked
    Customer_details cd = new Customer_details();
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cd.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cart_tbl;
    private javax.swing.JButton dlt_cart;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
